Repository zanata/zanata-mt, pull requests merged in 2018-08, with the labels that each got.

#84 chore: upgrade npm packages
  frontend/pom.xml
  frontend/src/package.json
  frontend/src/webpack.config.js
  frontend/src/yarn.lock
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#83 refactor: migrate username and password to account table
  README.md
  business-svc/src/main/java/org/zanata/magpie/service/AccountService.java
  business-svc/src/main/java/org/zanata/magpie/util/PasswordUtil.java
  business-svc/src/test/java/org/zanata/magpie/service/AccountServiceTest.java
  common/src/main/java/org/zanata/magpie/api/dto/AccountDto.java
  common/src/main/java/org/zanata/magpie/api/dto/CredentialDto.java
  mt-data/src/main/java/org/zanata/magpie/dao/AccountDAO.java
  mt-data/src/main/java/org/zanata/magpie/dao/CredentialDAO.java
  mt-data/src/main/java/org/zanata/magpie/model/Account.java
  mt-data/src/main/java/org/zanata/magpie/model/Credential.java
  mt-data/src/main/java/org/zanata/magpie/model/LocalCredential.java
  mt-data/src/main/resources/db/changelogs/db.changelog-1.1.xml
  mt-data/src/test/java/org/zanata/magpie/dao/AccountDAOTest.java
  server/src/main/java/org/zanata/magpie/api/security/SecurityInterceptor.java
  server/src/main/java/org/zanata/magpie/api/service/impl/AccountResourceImpl.java
  server/src/test/java/org/zanata/magpie/api/ValidatePayloadInterceptorTest.java
  server/src/test/java/org/zanata/magpie/api/security/SecurityInterceptorTest.kt
  server/src/test/java/org/zanata/magpie/api/service/impl/AccountResourceImplTest.java
  server/src/test/java/org/zanata/magpie/integration/AccountResourceITCase.kt
  server/src/test/java/org/zanata/magpie/integration/EnsureAdminAccountRule.kt
  server/src/test/java/org/zanata/magpie/integration/RestTest.kt
  server/src/test/java/org/zanata/magpie/service/EventRecordingServiceJpaTest.java
Labels: Reviewed, Verified

#85 feat(ZNTAMT-46): add support for text/xml
  business-svc/pom.xml
  business-svc/src/main/java/org/zanata/magpie/service/DocumentContentTranslatorService.java
  business-svc/src/main/java/org/zanata/magpie/service/PersistentTranslationService.java
  business-svc/src/main/java/org/zanata/magpie/service/StringTranslationResult.kt
  business-svc/src/main/java/org/zanata/magpie/service/TranslatableNodeList.java
  business-svc/src/main/java/org/zanata/magpie/util/ArticleUtil.java
  business-svc/src/test/java/org/zanata/magpie/service/DocumentContentTranslatorServiceTest.java
  business-svc/src/test/java/org/zanata/magpie/service/PersistentTranslationServiceTest.java
  business-svc/src/test/java/org/zanata/magpie/service/TranslatableHTMLNodeTest.java
  business-svc/src/test/java/org/zanata/magpie/util/ArticleUtilTest.java
  common/src/main/java/org/zanata/magpie/api/dto/TypeString.java
  common/src/main/java/org/zanata/magpie/model/Role.java
  common/src/main/java/org/zanata/magpie/model/StringType.java
  common/src/main/java/org/zanata/magpie/service/TranslatorBackend.java
  mt-engine/pom.xml
  mt-engine/src/main/java/org/zanata/magpie/backend/google/GoogleTranslatorBackend.java
  mt-engine/src/main/java/org/zanata/magpie/backend/mock/MockTranslatorBackend.java
  mt-engine/src/main/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackend.java
  mt-engine/src/test/java/org/zanata/magpie/backend/google/GoogleTranslatorBackendRealTest.java
  mt-engine/src/test/java/org/zanata/magpie/backend/google/GoogleTranslatorBackendTest.java
  mt-engine/src/test/java/org/zanata/magpie/backend/mock/MockTranslatorBackendTest.java
  mt-engine/src/test/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackendTest.java
  pom.xml
  rebuild.sh
  server/pom.xml
  server/src/test/java/org/zanata/magpie/integration/DocumentResourceITCase.kt
  server/src/test/java/org/zanata/magpie/service/PersistentTranslationServiceJpaTest.java
  server/src/test/java/org/zanata/magpie/util/ArticleUtilTest.java
Labels: Reviewed, Verified

#86 test: increase test coverage
  server/src/test/java/org/zanata/magpie/event/AccountCreatedTest.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#89 Handle text nodes
  business-svc/src/main/java/org/zanata/magpie/service/DocumentContentTranslatorService.java
  business-svc/src/main/java/org/zanata/magpie/util/ArticleUtil.java
  business-svc/src/test/java/org/zanata/magpie/service/DocumentContentTranslatorServiceTest.java
  business-svc/src/test/java/org/zanata/magpie/util/ArticleUtilTest.java
Labels: Reviewed, Verified

#88 update changelog to fix account constraint
  mt-data/src/main/resources/db/changelogs/db.changelog-1.1.xml
Labels: Reviewed, Verified

#90 Remove some eager loading
  business-svc/src/main/java/org/zanata/magpie/service/PersistentTranslationService.java
  business-svc/src/test/java/org/zanata/magpie/service/PersistentTranslationServiceTest.java
  mt-data/src/main/java/org/zanata/magpie/dao/DocumentDAO.java
  mt-data/src/main/java/org/zanata/magpie/model/Document.java
  mt-data/src/main/java/org/zanata/magpie/model/TextFlowMTRequest.java
  server/src/main/java/org/zanata/magpie/api/service/impl/DocumentResourceImpl.java
  server/src/test/java/org/zanata/magpie/api/service/DocumentResourceImplTest.java
  server/src/test/java/org/zanata/magpie/service/PersistentTranslationServiceJpaTest.java
Labels: Reviewed, Verified

#91 chore: lock parent image version
  server/Dockerfile
Labels: No QA (1st vote), No QA (2nd vote)

#92 feat(ZNTAMT-41): split large TextNodes into sentences
  business-svc/src/main/java/org/zanata/magpie/service/DocumentContentTranslatorService.java
  business-svc/src/main/java/org/zanata/magpie/util/SegmentString.java
  business-svc/src/main/java/org/zanata/magpie/util/SegmentString.kt
  business-svc/src/test/java/org/zanata/magpie/service/DocumentContentTranslatorServiceTest.java
  mt-data/src/main/java/org/zanata/magpie/model/Account.java
  mt-data/src/main/java/org/zanata/magpie/model/Document.java
  mt-data/src/main/java/org/zanata/magpie/model/Locale.java
  mt-data/src/main/java/org/zanata/magpie/model/ModelEntity.java
  mt-data/src/main/java/org/zanata/magpie/model/TextFlow.java
  mt-data/src/main/java/org/zanata/magpie/model/TextFlowTarget.java
  server/src/test/java/org/zanata/magpie/util/SegmentStringTest.java
  server/src/test/java/org/zanata/magpie/util/SegmentStringTest.kt
Labels: Reviewed, Verified

#77 file-upload
  .editorconfig
  business-svc/src/test/java/org/zanata/magpie/service/PersistentTranslationServiceTest.java
  business-svc/src/test/java/org/zanata/magpie/service/StringTranslationResultTest.kt
  business-svc/src/test/java/org/zanata/magpie/util/ArticleUtilTest.java
  business-svc/src/test/java/org/zanata/magpie/util/PasswordUtilTest.java
  business-svc/src/test/java/org/zanata/magpie/util/SegmentStringTest.kt
  business-svc/src/test/java/org/zanata/magpie/util/ShortStringTest.java
  common/pom.xml
  common/src/main/java/org/zanata/magpie/api/dto/TranslateDocumentForm.java
  common/src/main/java/org/zanata/magpie/api/service/BackendResource.java
  common/src/main/java/org/zanata/magpie/api/service/DocumentResource.java
  frontend/pom.xml
  frontend/src/app/actions/common.ts
  frontend/src/app/actions/info.ts
  frontend/src/app/actions/translateFile.ts
  frontend/src/app/components/Alert/index.tsx
  frontend/src/app/config.tsx
  frontend/src/app/constants/actions.ts
  frontend/src/app/containers/Info/index.tsx
  frontend/src/app/containers/LoginForm/index.tsx
  frontend/src/app/containers/NavBar/index.tsx
  frontend/src/app/containers/Translate/TranslateFile.tsx
  frontend/src/app/containers/index.ts
  frontend/src/app/history.tsx
  frontend/src/app/index.tsx
  frontend/src/app/reducers/common.ts
  frontend/src/app/reducers/index.ts
  frontend/src/app/reducers/info.ts
  frontend/src/app/reducers/translateFile.ts
  frontend/src/app/styles/index.less
  frontend/src/app/types/models.d.ts
  frontend/src/package.json
  frontend/src/yarn.lock
  mt-data/src/main/java/org/zanata/magpie/model/Document.java
  mt-engine/src/test/java/org/zanata/magpie/util/DTOUtilTest.java
  pom.xml
  server/pom.xml
  server/src/main/java/org/zanata/magpie/api/security/SecurityInterceptor.java
  server/src/main/java/org/zanata/magpie/api/service/impl/AccountResourceImpl.java
  server/src/main/java/org/zanata/magpie/api/service/impl/BackendResourceImpl.java
  server/src/main/java/org/zanata/magpie/api/service/impl/DocumentResourceImpl.java
  server/src/main/java/org/zanata/magpie/event/AccountCreated.java
  server/src/main/java/org/zanata/magpie/filter/PoFileAdapter.java
  server/src/main/java/org/zanata/magpie/filter/TranslationFileAdapter.java
  server/src/main/java/org/zanata/magpie/producer/ResourceProducer.java
  server/src/main/java/org/zanata/magpie/service/ConfigurationService.java
  server/src/test/java/org/zanata/magpie/api/security/SecurityInterceptorTest.kt
  server/src/test/java/org/zanata/magpie/api/service/impl/AccountResourceImplTest.java
  server/src/test/java/org/zanata/magpie/api/service/impl/BackendResourceImplTest.java
  server/src/test/java/org/zanata/magpie/api/service/impl/DocumentResourceImplTest.java
  server/src/test/java/org/zanata/magpie/api/service/impl/DocumentsResourceImplTest.java
  server/src/test/java/org/zanata/magpie/api/service/impl/InfoResourceImplTest.java
  server/src/test/java/org/zanata/magpie/api/service/impl/LanguagesResourceImplTest.java
  server/src/test/java/org/zanata/magpie/exception/DataConstraintViolationExceptionMapperTest.java
  server/src/test/java/org/zanata/magpie/filter/PoFileAdapterTest.java
  server/src/test/java/org/zanata/magpie/producer/ResourceProducerTest.java
  server/src/test/java/org/zanata/magpie/service/ConfigurationServiceTest.java
  server/src/test/java/org/zanata/magpie/service/MTStartupTest.java
  server/src/test/resources/test.pot
Labels: Reviewed, Verified

#96 Update JaCoCo (filters out Kotlin codegen)
  pom.xml
Labels: No QA (1st vote)

#93 fix(ZNTAMT-54): avoid need for psql on classpath
  business-svc/pom.xml
  business-svc/src/main/java/org/zanata/magpie/service/PersistentTranslationService.java
Labels: Reviewed, Verified

#94 fix(ZNTAMT-56): avoid Dependent scope for GoogleTranslatorBackend
  business-svc/src/main/java/org/zanata/magpie/service/PersistentTranslationService.java
  common/src/main/java/org/zanata/magpie/service/TranslatorBackend.java
  mt-engine/src/main/java/org/zanata/magpie/backend/google/GoogleTranslatorBackend.java
Labels: Reviewed, Verified
